### ISSUE TITLE
uninitialized constant CaskUnreadableError when trying to run brew scan-leftovers

### ISSUE THREAD

**Issue by hao-lh** [jysperm/homebrew-leftover-scanner#1]
**brew tap jysperm/leftover-scanner**
==> Tapping jysperm/leftover-scanner
Cloning into '/usr/local/Homebrew/Library/Taps/jysperm/homebrew-leftover-scanner'...
remote: Enumerating objects: 28, done.
remote: Counting objects: 100% (28/28), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 28 (delta 3), reused 28 (delta 3), pack-reused 0
Receiving objects: 100% (28/28), 409.01 KiB | 1.36 MiB/s, done.
Resolving deltas: 100% (3/3), done.
Tapped 1 command (14 files, 852.5KB).

**brew scan-leftovers**
Error: uninitialized constant CaskUnreadableError
/usr/local/Homebrew/Library/Taps/jysperm/homebrew-leftover-scanner/cmd/brew-scan-leftovers.rb:22:in `rescue in block in get_all_casks'
/usr/local/Homebrew/Library/Taps/jysperm/homebrew-leftover-scanner/cmd/brew-scan-leftovers.rb:21:in `block in get_all_casks'
/usr/local/Homebrew/Library/Taps/jysperm/homebrew-leftover-scanner/cmd/brew-scan-leftovers.rb:20:in `map'
/usr/local/Homebrew/Library/Taps/jysperm/homebrew-leftover-scanner/cmd/brew-scan-leftovers.rb:20:in `get_all_casks'
/usr/local/Homebrew/Library/Taps/jysperm/homebrew-leftover-scanner/cmd/brew-scan-leftovers.rb:77:in `<top (required)>'
/usr/local/Homebrew/Library/Homebrew/utils.rb:93:in `require'
/usr/local/Homebrew/Library/Homebrew/utils.rb:93:in `require?'
/usr/local/Homebrew/Library/Homebrew/brew.rb:95:in `<main>'

Could you help check this issue?
Thanks.

**Comment by liyishuai** [comment]
Same error logs here. My `brew config` is:
```
HOMEBREW_VERSION: 4.0.1-62-ga222a5b
ORIGIN: https://mirrors.aliyun.com/homebrew/brew.git
HEAD: a222a5bbc83923e4c9c09ed0ff07dfe64cf7d863
Last commit: 2 days ago
Core tap origin: https://mirrors.aliyun.com/homebrew/homebrew-core.git
Core tap HEAD: bcc0f7b5de81b165e33957291bd92ab46232dd89
Core tap last commit: 2 weeks ago
Core tap branch: master
Core tap JSON: 21 Feb 08:07 UTC
HOMEBREW_PREFIX: /usr/local
HOMEBREW_BOTTLE_DOMAIN: https://mirrors.ustc.edu.cn/homebrew-bottles
HOMEBREW_BREW_GIT_REMOTE: https://mirrors.aliyun.com/homebrew/brew.git
HOMEBREW_CASK_OPTS: []
HOMEBREW_CORE_GIT_REMOTE: https://mirrors.aliyun.com/homebrew/homebrew-core.git
HOMEBREW_MAKE_JOBS: 12
Homebrew Ruby: 2.6.10 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: dodeca-core 64-bit kabylake
Clang: 14.0.0 build 1400
Git: 2.39.2 => /usr/local/bin/git
Curl: 7.85.0 => /usr/bin/curl
macOS: 13.1-x86_64
CLT: 14.2.0.0.1.1668646533
Xcode: N/A
```

**Comment by jysperm** [comment]
I have made a [fix](https://github.com/jysperm/homebrew-leftover-scanner/commit/41d7471fdf9221deaa940606fa2b47f7dfc2ca34) that may solve this problem.

(Run `brew update` to get the latest version)

**Comment by hao-lh** [comment]
Thanks, it's working for me now :)
