### ISSUE TITLE
Error report for ClashX

### ISSUE THREAD

**Issue by woyin** [jysperm/homebrew-leftover-scanner#3]
When I run the command to find the leftover, i saw this one:
`==> Found leftovers from clashx, get rid of them via: brew uninstall -f --zap clashx`

In fact, ClashX is no removed, I still need to use it. 

And when I run the command `brew uninstall -f --zap clashx` and ru-run the ClashX, all the external sources are removed. I need to re-download all the external sources(includes the proxy and rules) to use ClashX.

**Comment by woyin** [comment]
Here is the running result.
<img width="695" alt="image" src="https://user-images.githubusercontent.com/35319250/220293544-428e17f8-b7f9-461d-9db7-836277580f59.png">

**Comment by jysperm** [comment]
According to [clashx.rb](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/clashx.rb), did you install it to `/Applications/ClashX.app` (not other paths)? If not, the scanner can't  know that ClashX is installed.

**Comment by woyin** [comment]
Yeah, I installed it to `/Applications/ClashX.app`, so should I use `brew install --cask clashx` to install it?
