### ISSUE TITLE
Warning: Calling Tap.default_cask_tap is deprecated! Use CoreCaskTap.

### ISSUE THREAD

**Issue by Mitsuhaxy** [jysperm/homebrew-leftover-scanner#7]
➜  ~ brew scan-leftovers   
Warning: Calling Tap.default_cask_tap is deprecated! Use CoreCaskTap.instance instead.
Please report this issue to the jysperm/leftover-scanner tap (not Homebrew/brew or Homebrew/homebrew-core), or even better, submit a PR to fix it:
  /opt/homebrew/Library/Taps/jysperm/homebrew-leftover-scanner/cmd/brew-scan-leftovers.rb:20

How can I fix it?

**Comment by weakish** [comment]
Reproduced on Homebrew 4.1.11

P.S. It's just a deprecation warning. You can just ignore it.
